<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerCratbnu\appProdProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerCratbnu/appProdProjectContainer.php') {
    touch(__DIR__.'/ContainerCratbnu.legacy');

    return;
}

if (!\class_exists(appProdProjectContainer::class, false)) {
    \class_alias(\ContainerCratbnu\appProdProjectContainer::class, appProdProjectContainer::class, false);
}

return new \ContainerCratbnu\appProdProjectContainer([
    'container.build_hash' => 'Cratbnu',
    'container.build_id' => '173eca3b',
    'container.build_time' => 1624197243,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerCratbnu');
